apiVersion: v1
kind: Namespace
metadata:
  name: app-ns
  labels:
    name: app-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-ns
  labels:
    name: data-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
